### ISSUE TITLE
Styling page_header/page_footer depending of the page number

### ISSUE THREAD

**Issue by fagundes** [spipu/html2pdf#114]
Question

For instance, I need to create a report which its even pages are aligned to the left, and its odd pages are aligned to right. Is there a way?

If there isnt.. Any ideas how to create it, so I can create a PR.

**Comment by juchi** [comment]
Hi,
If you have a way to know where the page breaks are while generating the html content (so, before calling html2pdf), you could just change the css rules depending on the page.
Otherwise, i don't think it's possible out of the box. However, by overloading the Html2Pdf class you could probably hook into the _setNewPage() method to implement a specific behavior, like an update of the current text align.

**Comment by fagundes** [comment]
Hi,  @juchi. 

I don't see a way to know where the page breaks because it's depending on data. The number of pages isn't fixed. And I may need to change also the page_footer/page_header content depending on page number. So, I agree with your second aproach I will need to overload the Html2Pdf class.

Thanks for answering.
