### ISSUE TITLE
pb output with absolute path

### ISSUE THREAD

**Issue by sfidry** [spipu/html2pdf#200]
Hello.

I have a problem with the output method when i try and absolute path like : 
'/XXXXXX_App/webapp_COMA_dta/SF/000004_/CTRVTEO001_000000000000000001758.pdf'

html2pdf add homedir in the path.
here my php.log

```
Stack trace:                                                                                                                        
#0 /XXXXXX_Dev/sfidry/negoces_webapp/vendor/tecnickcom/tcpdf/tcpdf.php(7675): TCPDF->Error('Unable to creat...')                    
#1 /XXXXXX_Dev/sfidry/negoces_webapp/vendor/spipu/html2pdf/src/Html2Pdf.php(508): TCPDF->Output('/home/SF//SAPAI...', 'F')          
#2 /XXXXXX_Dev/sfidry/negoces_webapp/webapp/modules/Z_Json2BoardTable.php(293): Spipu\Html2Pdf\Html2Pdf->output('/SAPAIG_App/web...'
#3 {main}                                                                                                                           
  thrown in /XXXXXX_Dev/sfidry/negoces_webapp/vendor/tecnickcom/tcpdf/tcpdf.php on line 2927      
```

I think the problem comes from theses lines in html2pdf.php

```
        // if save on server: it must be an absolute path
        if ($dest[0] == 'F') {
            if (!in_array($name, array('/', '\\'))) {
                $name = getcwd() . DIRECTORY_SEPARATOR . $name;
            }
        }

        // call the output of TCPDF
        return $this->pdf->Output($name, $dest);
```

**Comment by spipu** [comment]
arhhh sorry for this stupid bug :( i will fix it now

**Comment by spipu** [comment]
fixed in v5.0.1

is it ok for you ?

**Comment by sfidry** [comment]
It works fine.
thank you.

**Comment by UrvishSSPL** [comment]
When working in Windows environment, the absolute path does not always start with a slash ( / ). In such case, if the $name parameter contains absolute path of the output file, it attaches working directory before that path.
For example:
I have function named savePDF() which generates PDF file and store it to a local folder.

The web application root directory is `D:\app\` and the REST API root directory is `D:\app\API`, both are sharing same function.

```php
function savePDF() {
....
    $html2pdf->Output("D:/app/resoruces/temp/abcd.pdf", "F");
...
}
```
When I call this function from my webpage, it gives an error as it is trying to write file at location `D:\app/D:/app/resoruces/temp/abcd.pdf`, because `D:\app` is my working directory

When I call this function from my API, it gives an error as it is trying to write file at location `D:\app\API/D:/app/resoruces/temp/abcd.pdf`, because `D:\app\API` is my working directory.

**Comment by dhope0000** [comment]
Im currently using this work around for anyone on windows; 
```
        //https://stackoverflow.com/questions/5879043/php-script-detect-whether-running-under-linux-or-windows
        // if save on server: it must be an absolute path
        if ($dest[0] == 'F' && $name[0] !== DIRECTORY_SEPARATOR) {
            // If this isn't a windows machine do the concatination
            if (strtoupper(substr(PHP_OS, 0, 3)) !== "WIN") {
                $name = getcwd() . DIRECTORY_SEPARATOR . $name;
            }
        }
``` 

To use this just go to Html2Pdf.php and replace the code around line 500 (in the function "output")

**Comment by spipu** [comment]
Hi 

Thanks for this solution.

Could you make a PR ?

**Comment by dhope0000** [comment]
I can, do you want some regex that trys to check for a leter E.G "C:\" or just as is ?

**Comment by spipu** [comment]
The regex is a good idea [A-Z]:\
