### ISSUE TITLE
$line = fgetcsv($handle); if (null != $line && count($line)!=2) { continue; }

### ISSUE THREAD

**Issue by tombosoadimitrie** [spipu/html2pdf#280]
https://github.com/spipu/html2pdf/blob/b0040892c89d34bc3f90247d7ab6505aa3d80c9c/src/Locale.php#L85

**Comment by tombosoadimitrie** [comment]
$line = fgetcsv($handle); if (null != $line && count($line)!=2) { continue; }

**Comment by spipu** [comment]
Yes, and ?

**Comment by dennisheiden** [comment]
Doesn't make any sense. No valid headline provided, description of the "issue" is missing.

I would just delete that issue.

Btw. `null != $line && count($line)!=2` doesn't make sense here, 
we want to know if $line is not an array (is_array(null) = false anyway) OR if the entry count is not equal 2. Only way to pass that clause is to return an array with exact 2 elements. Everything else will trigger the continue statement.

` if (null != $line && count($line)!=2)` would only match NULL if count() is != 2. This will never happen,
because count() only works with arrays or countable objects.

**Comment by MBCNL** [comment]
It seems that Array $line contains sometimes a boolean so lets handle it the right way.
`if (is_bool($line) || count($line)!=2) continue;` this way we first check if the var is a boolean before counting anything.

**Comment by spipu** [comment]
It has been fixed in the last version
