### ISSUE TITLE
Genreated PDF different than viewed PDF

### ISSUE THREAD

**Issue by griffin34** [spipu/html2pdf#30]
The forum is not working, so maybe some help here.

 I am trying to generate a PDF, with ul li.  I have the stlye="float:left" on the li objects.  When rendering in the bowser ($llama->writeHTML($content,true);

The li objects stack the way I intended.  When the PDF is generated, they do not stack, and it appears that the text is overwriting itself.

Any help would be greatly appreciated.

**Comment by fagundes** [comment]
@griffin34 I didn't used floating in html2pdf yet but it seems to work just fine. You could debug using borders at the ul tag and the li tags to see better what its happening. Also check if there is a typo like 'stlye' instead of 'style' or something like that. :smile: 

If you couldn't solve this put more about your code so we can be able to replicate the error.

**Comment by juchi** [comment]
Hi,
The float attribute is currently only supported for images and won't have any effect on other html tags.
It's a feature I would like to add in version 5, but we first have quite some work finishing the code rewrite for this to be possible.
For now, working with tables like in the (not so) good old days is a way to achieve a similar effect.
Regards

**Comment by spipu** [comment]
float elements are very difficult to render, and can be avoid because you generate a PDF in a specific size => it has not to adapt automatically 

Use the table instead.

Remember that you havt to write the HTML for HTML2PDF, not directly using a html that has been written for browsers
