### ISSUE TITLE
Php 7.3+ and tc-lib-pdf support

### ISSUE THREAD

**Issue by EoleDev** [spipu/html2pdf#495]
Hi,
Thanks for your work!!
We are currently updating our application using your library,
and we would like to know if you plan to support PHP 7.3+ versions
and the new tc-lib-pdf library (which will replace tcpdf).

**Comment by LittleBigFox** [comment]
Hi!

I'm going to use php7.3 in a few days, i'll try to update and commit as soon as possible.
For tc-lib-pdf, it's still in dev, i think our spipu will wait until the final dev, or at least last RC.

Regards,
LBF

**Comment by EoleDev** [comment]
Thank you for your answer,
The php7.3 support is not urgent for us.
I just wanted to be sure your library would be updated with 7.3 and tc-lib-pdf (when it will be released).

Thank you for your work!

**Comment by lenamtl** [comment]
Hi,

I have checked the changelog from https://github.com/tecnickcom/TCPDF/blob/master/CHANGELOG.TXT 
so since TCPDF v 6.2.19 this was working with PHP 7.3

I have checked my package and I'm using TCPDF v6.2.13
Suggestion maybe just updating to 6.2.19 version could do the trick for now.
What do you think?

I don't think the newest library will be available soon and as it is a new library it may take time for you to update your scripts too ...
https://github.com/tecnickcom/tc-lib-pdf
