### ISSUE TITLE
html table with 40'000 rows

### ISSUE THREAD

**Issue by webfondue** [spipu/html2pdf#97]
I tried to use html2pdf.fr to create a pdf for a table with about 40'000 rows. Unfortunately it takes to much time. for about 1'000 Records I just have to wait about one minute and the CPU-load of the server is about 99%. Does anyone has an idea to perform the creation? The table is quite simple without any css.

**Comment by juchi** [comment]
Hi,
Table generation is indeed a quite heavy process in HTML2PDF and unfortunately there no major improvement to be expected for now, with the current code base.
However, performance for heavy documents will be one of the focuses for the next major version, but I can't provide a timeline at this time.

**Comment by mhagenbruch** [comment]
Hey there, i have the same problem. What is better tags to use than table? simple divs?

**Comment by fagundes** [comment]
@mhagenbruch, sorry for the late reply, I don't think change the tag name will really improve the performance. My guess the recursive algorithm is the problem here. 

I guess the real 'bottleneck' to use html2pdf now it's their performance in large documents. There is any kind of guideline that we could pursue to contribuite to improve html2pdf in that matter.

There are some issue we can solve improving it. This one, #135 and #133.

**Comment by spipu** [comment]
html2pdf does not like big tables. Try to split them in tables of 100 rows
